name: Build Mac Executable

on:
  push:
    branches: [ master ]  # Triggers on push to main branch
  workflow_dispatch:    # Allows manual triggering

jobs:
  build-mac:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller
        
    - name: Build executable
      run: |
        pyinstaller --onefile --windowed --add-data "images/esc-logo.png:images" --name "Auto House Champs" --icon images/esc-logo.png main/run.py

    - name: Create DMG
      run: |
        mkdir -p dmg-contents
        cp -R "dist/Auto House Champs.app" dmg-contents/
        hdiutil create -volname "Auto House Champs" -srcfolder dmg-contents -ov -format UDZO "Auto House Champs.dmg"

    - name: Upload Mac executable
      uses: actions/upload-artifact@v4
      with:
        name: mac-executable
        path: 'Auto House Champs.dmg'
        retention-days: 30  # How long GitHub keeps the artifact
